FROM prom/alertmanager:latest

# Install gettext for envsubst
USER root
RUN apk add --no-cache gettext

# Copy entrypoint script
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

USER nobody
ENTRYPOINT ["/entrypoint.sh"]
